server:
  port: 80
spring:
  profiles:
    active: test
profile: 正式版本

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka